version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeTestPro
  gitServerName: testProject
  gitUrl: https://github.com/rlakshitha0912/EdgeTestPro
  gitUsername: rlakshitha0912
  gitBranch: main
